#!/bin/tcsh

#For temperature-REMD read temperature file  
sed 1,2d temperatures_short.dat > temp-list.dat

set SANDER=`which pmemd.MPI`
set SANDER_GPU=`which pmemd.cuda`
set MDIR=`pwd`
#echo $SANDER

set PREV=srt
set DPRE=srt
set TYP=gvpgv

#Minimization step for all the temperatures

foreach RUN (min1 min2 min3 min4)
   echo Doing $RUN now
   echo ==============
   mkdir $RUN
   cp files/$RUN.in $RUN/
   cd $RUN
   ln -s ../Struct/$TYP.top .
   ln -s ../$PREV/$TYP.crd.$PREV .

       if ($RUN == min1 || $RUN == min2 || $RUN == min3 || $RUN == min4) then
               ln -s ../$PREV/$TYP.crd.$PREV $TYP.crd.rst
       endif

       if ($RUN == min1 || $RUN == min2) then
          mpirun -np 16 $SANDER -i $RUN.in -o $RUN.out \
          -p $TYP.top -c $TYP.crd.$PREV -r $TYP.crd.$RUN -ref $TYP.crd.rst &
       else
          $SANDER_GPU -i $RUN.in -o $RUN.out \
          -p $TYP.top -c $TYP.crd.$PREV -r $TYP.crd.$RUN -ref $TYP.crd.rst &
       endif
   sleep 900s
   set DPRE=$PREV
   set PREV=$RUN
   cd ..
end

# Start individual equilibrations for each target temperature window

set NUMREP=`wc -l < temp-list.dat`
echo $NUMREP
set PREV=min4

foreach REP ( `seq 1 $NUMREP` )
  foreach RUN (md1 md2 min11 md11 min12 md12 min13 md13 min14 md14)
     echo Doing $RUN now
     echo ==============
if ($RUN == min11 || $RUN == min12 || $RUN == min13 || $RUN == min14) then
          cp files/$RUN.in files/$RUN"rep".$REP.in
     else
          python genremdinputs.py -inputs temperatures_short.dat -groupfile groupfile.ref -i files/$RUN.ref -O
     endif
     if ($REP == 1) then
        mkdir $RUN
     endif
     cp files/$RUN"rep".$REP.in $RUN/
     cd $RUN
     ln -s ../Struct/$TYP.top .
      if ($RUN == md1) then
              set PREV=min4
              ln -s ../$PREV/$TYP.crd.$PREV $TYP.crd.$PREV"rep".$REP.rst
              ln -s ../$PREV/$TYP.crd.$PREV $TYP.crd.$PREV"rep".$REP
      endif

       if ($RUN == md2 || $RUN == min11) then
              ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP .
              ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP $TYP.crd.rep.$REP.rst
         endif

         if ($RUN == min12 || $RUN == min13 || $RUN == min14 || $RUN == min15 || $RUN == md16) then
              ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP .
              ln -s ../$DPRE/$TYP.crd.$DPRE"rep".$REP $TYP.crd.rep.$REP.rst
         endif

         if ($RUN == md11 || $RUN == md12 || $RUN == md13 || $RUN == md14 || $RUN == md15) then
             ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP .
             ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP $TYP.crd.rep.$REP.rst
         endif

        if ($RUN == md1) then
            $SANDER_GPU -i $RUN"rep".$REP.in -o $RUN"rep".$REP.out \
            -p $TYP.top -c $TYP.crd.$PREV"rep".$REP -r $TYP.crd.$RUN"rep".$REP -ref $TYP.crd.$PREV"rep".$REP &
        endif

        if ($RUN == md2 || $RUN == min11 || $RUN == md11 || $RUN == min12 || $RUN == md12 || $RUN == min13 || $RUN == md13 || $RUN == min14 || $RUN == md14) then
            $SANDER_GPU -i $RUN"rep".$REP.in -o $RUN"rep".$REP.out \
            -p $TYP.top -c $TYP.crd.$PREV"rep".$REP -r $TYP.crd.$RUN"rep".$REP -ref $TYP.crd.$PREV"rep".$REP &
        endif

     sleep 900s
     mv mdcrd rep$REP.mdcrd
     mv mden rep$REP.mden
     mv mdinfo rep$REP.mdinfo
     set DPRE=$PREV
     set PREV=$RUN
     cd ..
end
end

# Running replica exchange  
python genremdinputs.py -inputs temperatures_short.dat -groupfile groupfile.ref -i files/groupfile.ref -O

mpirun -np 8 pmemd.cuda_SPFP.MPI -ng 8 -groupfile groupfile -rem 1

