#!/bin/tcsh

#For temperature-REMD read temperature file  
sed 1,2d temperatures_short.dat > temp-list.dat

set SANDER=`which pmemd.MPI`
set SANDER_GPU=`which pmemd.cuda`
set MDIR=`pwd`
#echo $SANDER

set PREV=srt
set DPRE=srt
set TYP=gvpgv

#Minimization step for all the temperatures

foreach RUN (min1 min2 min3 min4)
   echo Doing $RUN now
   echo ==============
     if ($RUN == min11 || $RUN == min12 || $RUN == min13 || $RUN == min14) then
          cp files/$RUN.in files/$RUN"rep".$REP.in
     else
          python genremdinputs.py -inputs temperatures_short.dat -groupfile groupfile.ref -i files/$RUN.ref -O
     endif
     if ($REP == 1) then
        mkdir $RUN
     endif
     cp files/$RUN"rep".$REP.in $RUN/
     cd $RUN
     ln -s ../Struct/$TYP.top .
      if ($RUN == md1) then
              ln -s ../$PREV/$TYP.crd.$PREV $TYP.crd.$PREV"rep".$REP.rst
              ln -s ../$PREV/$TYP.crd.$PREV $TYP.crd.$PREV"rep".$REP
      endif

       if ($RUN == md2 || $RUN == min11) then
              ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP .
              ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP $TYP.crd."rep".$REP.rst
         endif

         if ($RUN == min12 || $RUN == min13 || $RUN == min14 || $RUN == min15 || $RUN == md16) then
              ln -s ../$DPRE/$TYP.crd.$PREV"rep".$REP .
              ln -s ../$DPRE/$TYP.crd.$DPRE"rep".$REP $TYP.crd.rep.$REP.rst
         endif

         if ($RUN == md11 || $RUN == md12 || $RUN == md13 || $RUN == md14 || $RUN == md15) then
             ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP .
             ln -s ../$PREV/$TYP.crd.$PREV"rep".$REP $TYP.crd.rep.$REP.rst
         endif

        if ($RUN == md1) then
            $SANDER_GPU -i $RUN"rep".$REP.in -o $RUN"rep".$REP.out \
            -p $TYP.top -c $TYP.crd.$PREV"rep".$REP -r $TYP.crd.$RUN"rep".$REP -ref $TYP.crd.$PREV"rep".$REP &
            sleep 900s
            mv mdcrd rep$REP.mdcrd
            mv mden rep$REP.mden
            mv mdinfo rep$REP.mdinfo
        endif

        if ($RUN == md2 || $RUN == min11 || $RUN == md11 || $RUN == min12 || $RUN == md12 || $RUN == min13 || $RUN == md13 || $RUN == min14 || $RUN == md14) then
            $SANDER_GPU -i $RUN"rep".$REP.in -o $RUN"rep".$REP.out \
            -p $TYP.top -c $TYP.crd.$PREV"rep".$REP -r $TYP.crd.$RUN"rep".$REP -ref $TYP.crd.$PREV"rep".$REP &
            sleep 900s
            mv mdcrd rep$REP.mdcrd
            mv mden rep$REP.mden
            mv mdinfo rep$REP.mdinfo
        endif

     set DPRE=$PREV
     set PREV=$RUN
     cd ..
end
end

# Running replica exchange  
python genremdinputs.py -inputs temperatures_short.dat -groupfile groupfile.ref -i files/groupfile.ref -O

mpirun -np 8 pmemd.cuda_SPFP.MPI -ng 8 -groupfile groupfile -rem 1

